#!/usr/bin/bash

# Ingest and transcode footage from Mini 3 Pro (H.264/H265 mp4) to MPEG4 mov, and copy subtitles

model='mini-3-pro'
date=$(date '+%Y-%m-%d')
source=/run/media/hannes/*/DCIM/100MEDIA
target=/mnt/media/drone-footage/$model/$date

mkdir -p $target
for i in $source/*.MP4; do
    ffmpeg -i "$i" -q:v 31 -c:v mpeg4 $target/$(basename ${i%.*}).mov
done

cp $source/*.SRT $target
